name: Pull Request Check

on: [pull_request]

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check modified files
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} | grep -E '^(build/|src/)' > /dev/null
        if [ $? -ne 0 ]; then
          echo "Pull Request contains changes outside 'build/' and 'src/' directories."
          exit 1
        fi

    - name: Check group_name folder modifications
      run: |
        git fetch origin ${{ github.base_ref }}
        CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} | grep -E '^build/group_name|^src/group_name')
        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes in specified directories."
          exit 0
        else
          echo "Changes detected in specified directories:"
          echo "$CHANGED_FILES"
          exit 1
        fi
