name: Pull Request Check

on: [pull_request]

jobs:
  check-modified-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check modified files
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} | grep -E '^(build/|src/)' > /dev/null
        if [ $? -ne 0 ]; then
          echo "Pull Request contains changes outside 'build/' and 'src/' directories."
          exit 1
        fi

    - name: Check group_name folder modifications
      run: |
        echo "Fetching origin/${{ github.base_ref }}"
        git fetch origin ${{ github.base_ref }}
    
        echo "Listing changed files from origin/${{ github.base_ref }}"
        CHANGED_FILES_LIST=$(git diff --name-only origin/${{ github.base_ref }})
        
        echo "List of changed files:"
        echo "$CHANGED_FILES_LIST"
    
        echo "Filtering changed files for specific directories"
        if echo "$CHANGED_FILES_LIST" | grep -E '^build/group_name|^src/group_name'; then
          echo "Changes detected in specified directories."
          exit 1
        else
          echo "No changes in specified directories."
          exit 0
        fi

  
